# ResVSS-UNet config

# Model name
name: resvss_unet

# I/O
out_channels: ${out_channels}

# Encoder
encoder: ResNet34

#Patches
enc_channels: [64, 64, 128, 256, 512]
dims: [96, 192, 384, 768]
patch_size: 2

# Decoder
dims_decoder: [768, 384, 192, 96]
depths_decoder: [2,2,2,2]

# Drop path rate
drop_path_rate: 0.2

# Pretrained ckpt
pretrained_ckpt: vmamba_small_e238_ema.pth
